"""Reference data for the storage finder: data classification levels and the
catalog of storage services available at the university."""

CLASSIFICATIONS = {
    "unrestricted": {
        "label": "Unrestricted",
        "summary": "Data intended for general use within the university.",
        "examples": [
            "Directory information",
            "Website pages",
            "Syllabi",
            "Schedule of classes",
        ],
        "policy": "May use third-party services in normal business without a university contract.",
        "note": (
            "All research data that has not been previously classified is currently "
            "treated as Unrestricted. It may have to be reclassified in the future."
        ),
    },
    "sensitive": {
        "label": "Sensitive",
        "summary": (
            "Data commonly used to conduct university business that, by its nature or "
            "regulation, carries an expected obligation of non-disclosure outside of "
            "authorized individuals."
        ),
        "policy": (
            "Third-party platforms only when there is a legitimate business need that "
            "university systems cannot meet. Grant access on a least-privilege basis."
        ),
        "examples": [
            "Data protected under FERPA",
            "Employment applications",
            "Employee performance evaluations",
            "Confidential donor information",
            "IRB Level 2 human subjects research data",
            "Minutes from confidential meetings",
            "Misconduct accusations / investigation records",
            "Date of birth, place of birth, mother's maiden name",
            "Personally identifiable demographic information",
            "Admissions applications",
            "Privileged attorney-client communications",
            "ID photos",
        ],
    },
    "confidential": {
        "label": "Confidential",
        "summary": (
            "The most restrictive classification. Data that could cause serious harm to "
            "the university or individuals if disclosed to those lacking authorized access."
        ),
        "policy": (
            "Generally kept on university-owned and maintained systems. A third-party or "
            "cloud service needs approval from central IT leadership and a security assessment."
        ),
        "examples": [
            "Social Security Number",
            "Driver's license / state-issued ID number",
            "Visa / passport number",
            "Credit card or bank account number",
            "Health insurance policy number",
            "Income tax records",
            "Personally identifiable health or genetic information",
            "Classified research data",
            "Controlled Unclassified Information (CUI)",
            "IRB Level 3 human subjects research data",
            "Export-controlled / ITAR research data",
        ],
    },
}

# classification_status values:
#   ok      -> fully permitted
#   review  -> permitted but requires review/approval, or "check with your IT support"
#   no      -> never store this classification of data here

STORAGE_OPTIONS = [{'id': 'box',
  'name': 'Box',
  'short_name': 'Box',
  'vendor': 'Box',
  'category': 'Cloud file sharing',
  'tagline': 'Cloud file storage and sharing for individuals and groups.',
  'description': 'Cloud storage and file sharing with external sharing links. The university now recommends '
                 'OneDrive for business files, and Box is not meant to replace OneDrive or on-campus data '
                 'servers.',
  'cost': 'Free',
  'capacity_label': 'Unlimited storage; files up to 15 GB each',
  'backup_available': True,
  'backup_note': 'Versioned automatically; deleted files are recoverable for a limited time.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'review'},
  'audiences': ['individual', 'team', 'external'],
  'volumes': ['small', 'medium', 'large'],
  'purposes': ['everyday'],
  'pros': ['Easy external sharing', 'Works well for collaboration', 'Available anywhere'],
  'cons': ['Confidential data needs security review first',
           'Being phased out: OneDrive is the recommended platform',
           'When you leave, your account shrinks to a free 5 GB plan',
           'Not built for research computing'],
  'accent': '#0061D5',
  'pricing': 'quota',
  'eligibility': 'Students, faculty, staff, and administrators',
  'how_to': 'Sign in with your university credentials.'},
 {'id': 'onedrive',
  'name': 'Microsoft OneDrive',
  'short_name': 'OneDrive',
  'vendor': 'Microsoft',
  'category': 'Cloud file sharing',
  'tagline': 'Personal cloud drive integrated with Microsoft 365.',
  'description': 'Your personal cloud drive, synced across devices and integrated with Word, Excel, '
                 "PowerPoint and Teams. It is the university's recommended platform for business files.",
  'cost': 'Free',
  'capacity_label': 'Per-user quota set by IT; extra storage may be available',
  'backup_available': True,
  'backup_note': 'File versioning and a recoverable recycle bin are built in.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'ok'},
  'audiences': ['individual', 'team'],
  'volumes': ['small', 'medium'],
  'purposes': ['everyday'],
  'pros': ['Approved for all classification levels',
           'Recommended by IT for business files',
           'Deep Microsoft Office integration',
           'Simple sync client'],
  'cons': ['Not designed for large research datasets',
           'Sharing is limited to people inside the university',
           'Transfer your files before you leave, or they are lost'],
  'accent': '#0078D4',
  'pricing': 'quota',
  'eligibility': 'Students, faculty, staff, and administrators',
  'how_to': 'Sign in to Microsoft 365 with your university credentials.'},
 {'id': 'sharepoint',
  'name': 'Microsoft SharePoint',
  'short_name': 'SharePoint',
  'vendor': 'Microsoft',
  'category': 'Cloud file sharing',
  'tagline': 'Team and project sites for group collaboration.',
  'description': 'Team and project sites (Hub, Communication, or Team) with document libraries, permissions, '
                 'and workflows for internal collaboration.',
  'cost': 'Free',
  'capacity_label': 'About 100 GB per site',
  'backup_available': True,
  'backup_note': 'File versioning and a recoverable recycle bin are built in.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'ok'},
  'audiences': ['team'],
  'volumes': ['small', 'medium', 'large'],
  'purposes': ['everyday'],
  'pros': ['Approved for all classification levels',
           'Great for team/project collaboration',
           'Easy sharing and permissions inside the university'],
  'cons': ['Sharing outside the university is limited; check with IT',
           "Overkill for one person's files",
           'Site structure takes some setup'],
  'accent': '#038387',
  'pricing': 'quota',
  'eligibility': 'Anyone with a university account',
  'how_to': 'Sign in to Microsoft 365, or ask your IT support to create a team site.'},
 {'id': 'tier1',
  'name': 'Tier 1 Research Storage',
  'short_name': 'Tier 1',
  'vendor': 'Vast',
  'category': 'University-managed research storage',
  'tagline': 'High-performance, all-flash storage for active research computing.',
  'description': 'The fastest storage tier, built on all-flash hardware and attached to high-performance '
                 'computing resources for workloads that need low latency and high throughput.',
  'cost': 'Paid, billed per TB',
  'capacity_label': 'Scalable from TB to PB',
  'backup_available': True,
  'backup_note': 'Snapshot-based recovery; ask your research computing team about full backup add-ons.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'no', 'confidential': 'no'},
  'audiences': ['individual', 'team'],
  'volumes': ['medium', 'large', 'xlarge'],
  'purposes': ['hpc'],
  'pros': ['Lowest latency / highest throughput',
           'Directly attached to compute clusters',
           'Scales to large datasets'],
  'cons': ['Highest cost per TB', 'Unrestricted data only: not for sensitive or confidential data'],
  'accent': '#D73F09',
  
  'pricing': 'paid',
  'how_to': 'Request a consultation with research computing support.',
  'eligibility': 'University researchers'},
 {'id': 'tier2',
  'name': 'Tier 2 Research Storage',
  'short_name': 'Tier 2',
  'vendor': 'PowerScale',
  'category': 'University-managed research storage',
  'tagline': 'Standard-performance storage for departments and research groups.',
  'description': "The university's low-cost shared file service for research data. The first 100 GB is free, "
                 'and additional capacity is billed per GB per year.',
  'cost': 'First 100 GB free, then about $0.06 per GB per year (about $61 per TB)',
  'capacity_label': '100 GB free, then scalable to many TB',
  'backup_available': True,
  'backup_note': 'Hourly, daily and weekly snapshots kept for 30 days.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'review'},
  'audiences': ['individual', 'team'],
  'volumes': ['small', 'medium', 'large', 'xlarge'],
  'purposes': ['hpc', 'everyday'],
  'pros': ['Good balance of cost and performance',
           'Hourly, daily, and weekly snapshots',
           'Good default for departmental shares'],
  'cons': ['Slower than Tier 1 for demanding compute jobs', 'Confidential data needs IT review first'],
  'accent': '#EA6A20',
  'review_note': 'check with your IT support',
  'pricing': 'both',
  'eligibility': 'University researchers',
  'how_to': 'Request a consultation with research computing support.'},
 {'id': 'tier3',
  'name': 'Tier 3 Research Storage',
  'short_name': 'Tier 3',
  'vendor': 'Ceph',
  'category': 'University-managed research storage',
  'tagline': 'Lower-cost, higher-capacity storage for archival and bulk data.',
  'description': 'Object/bulk storage optimized for cost-per-TB rather than speed — a strong fit for large '
                 'datasets that are written once and read infrequently.',
  'cost': 'Paid, lowest cost per TB',
  'capacity_label': 'Scalable to multiple PB',
  'backup_available': False,
  'backup_note': 'Data redundancy via erasure coding, not a traditional backup — keep a second copy of '
                 'anything irreplaceable.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'no', 'confidential': 'no'},
  'audiences': ['individual', 'team'],
  'volumes': ['medium', 'large', 'xlarge'],
  'purposes': ['archive'],
  'pros': ['Lowest cost per TB', 'Scales to very large datasets', 'Good backup/archive target'],
  'cons': ['Higher latency, not for active compute', 'Not a substitute for real backup', 'Unrestricted data only: not for sensitive or confidential data'],
  'accent': '#4A4A48',
  
  'pricing': 'paid',
  'how_to': 'Request a consultation with research computing support.',
  'eligibility': 'University researchers'},
 {'id': 'shared_drive',
  'name': 'Departmental Shared Drive',
  'short_name': 'Shared Drive',
  'vendor': 'Network file share',
  'category': 'University-managed file storage',
  'kind': 'storage',
  'specialty': None,
  'tagline': 'The shared network drive (file share) run by your department or unit.',
  'description': 'A mapped network drive managed by your local IT support team, commonly used for department '
                 'documents, forms, and shared working files.',
  'cost': 'Varies by department',
  'capacity_label': "Set by your department's IT support",
  'backup_available': True,
  'backup_note': 'Backed up by your IT support team; ask about the schedule and retention.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'review'},
  'audiences': ['individual', 'team'],
  'volumes': ['small', 'medium', 'large'],
  'purposes': ['everyday'],
  'pros': ['Familiar drive-letter access',
           'Managed by local IT support',
           'Can hold confidential data with IT sign-off'],
  'cons': ['Usually only reachable on campus or through VPN',
           'Confidential data needs a check with your IT support',
           'Limited external sharing'],
  'accent': '#5B6770',
  'review_note': 'check with your IT support',
  'pricing': 'quota',
  'eligibility': 'Members of the department or unit that runs it',
  'how_to': "Ask your department's IT support for access to the shared drive."},
 {'id': 'google_drive',
  'name': 'Google Drive / Docs',
  'short_name': 'Google Drive',
  'vendor': 'Google',
  'category': 'Cloud file sharing',
  'kind': 'storage',
  'specialty': None,
  'tagline': 'Cloud documents and file sharing with real-time co-editing.',
  'description': "Google's cloud file storage and document editing. It is deprecated at the university and "
                 'is not on the central services list.',
  'cost': 'Free',
  'capacity_label': 'About 2 GB per account (some older accounts are larger)',
  'backup_available': True,
  'backup_note': 'Version history; deleted files recoverable for a limited time.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'no'},
  'audiences': ['individual', 'team', 'external'],
  'volumes': ['small'],
  'purposes': ['everyday'],
  'pros': ['Excellent real-time co-editing', 'Easy sharing with anyone'],
  'cons': ['Deprecated: move to OneDrive', 'Small quota', 'Not approved for confidential data'],
  'accent': '#1A73E8',
  'pricing': 'quota',
  'eligibility': 'Existing university Google accounts',
  'how_to': 'Existing accounts only. The university advises moving files to OneDrive.'},
 {'id': 'slack',
  'name': 'Slack',
  'short_name': 'Slack',
  'vendor': 'Slack',
  'category': 'Messaging and chat',
  'kind': 'application',
  'specialty': 'Team chat, not file storage',
  'tagline': 'Team chat and quick file sharing.',
  'description': 'Team messaging with channels and file drops. It is a conversation tool, not an archive.',
  'cost': 'Varies by college or department',
  'capacity_label': 'Workspace limits apply',
  'backup_available': False,
  'backup_note': 'Not a backup. Messages and files may expire under workspace retention rules.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'no', 'confidential': 'no'},
  'audiences': ['team'],
  'volumes': ['small'],
  'purposes': ['everyday'],
  'pros': ['Fast team communication', 'Easy to drop a file into a conversation'],
  'cons': ['Unrestricted data only', 'Not a place to keep files long term'],
  'accent': '#4A154B',
  'pricing': 'quota',
  'eligibility': 'Varies by college or department',
  'how_to': 'Ask your college or department IT support. There is no central Slack service.'},
 {'id': 'qualtrics',
  'name': 'Qualtrics',
  'short_name': 'Qualtrics',
  'vendor': 'Qualtrics',
  'category': 'Research application',
  'kind': 'application',
  'specialty': 'Survey data only',
  'tagline': 'Survey design and survey response data.',
  'description': "The university's survey platform. Use it to collect responses, and export results to "
                 'proper storage.',
  'cost': 'Free',
  'capacity_label': 'Survey response limits apply',
  'backup_available': True,
  'backup_note': 'Managed by the platform; export final data to long-term storage.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'review'},
  'audiences': ['individual', 'team', 'external'],
  'volumes': ['small', 'medium'],
  'purposes': ['everyday'],
  'pros': ['Purpose-built for surveys', 'Approved for sensitive data'],
  'cons': ['Confidential data needs review and approval', 'Only for survey data'],
  'accent': '#00B4EF',
  'pricing': 'quota',
  'eligibility': 'Students, faculty, staff, and administrators',
  'how_to': 'Sign in with your university credentials. An account is created on your first login.'},
 {'id': 'onbase',
  'name': 'OnBase',
  'short_name': 'OnBase',
  'vendor': 'Hyland',
  'category': 'Records management',
  'kind': 'application',
  'specialty': 'Official records and forms workflows',
  'tagline': 'Document imaging and records workflows.',
  'description': 'Enterprise content management with document versioning, retention management and '
                 'workflows. It connects to the student information system, DocuSign and other systems.',
  'cost': 'Free to employees',
  'capacity_label': 'Set by the records program',
  'backup_available': True,
  'backup_note': 'Managed centrally as an official records system.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'review'},
  'audiences': ['team'],
  'volumes': ['small', 'medium'],
  'purposes': ['archive', 'everyday'],
  'pros': ['Records-grade retention', 'Approved for sensitive data'],
  'cons': ['Confidential data needs review and approval',
           'Set up through a records or business process, not self-service'],
  'accent': '#7A2E8E',
  'pricing': 'quota',
  'eligibility': 'University employees only',
  'how_to': "Sign in through the vendor's cloud portal with your university account."},
 {'id': 'canvas',
  'name': 'Canvas',
  'short_name': 'Canvas',
  'vendor': 'Instructure',
  'category': 'Learning management',
  'kind': 'application',
  'specialty': 'Course materials only',
  'tagline': 'Course materials and student coursework.',
  'description': 'The learning management system for course content, assignments, and grades.',
  'cost': 'Free (institutionally licensed)',
  'capacity_label': 'Course file limits apply',
  'backup_available': True,
  'backup_note': 'Managed by the platform for the life of the course.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'no'},
  'audiences': ['team', 'external'],
  'volumes': ['small', 'medium'],
  'purposes': ['everyday'],
  'pros': ['Built for teaching', 'Approved for sensitive data such as student records'],
  'cons': ['Not approved for confidential data', 'Only for course content'],
  'accent': '#E4002B',
  'pricing': 'quota',
  'how_to': 'Your courses appear automatically when you sign in.'},
 {'id': 'docusign',
  'name': 'DocuSign',
  'short_name': 'DocuSign',
  'vendor': 'DocuSign',
  'category': 'Records management',
  'kind': 'application',
  'specialty': 'Documents that need signatures',
  'tagline': 'Electronic signatures and signed documents.',
  'description': 'Send agreements for signature and keep the completed, signed copies.',
  'cost': 'Free',
  'capacity_label': 'Envelope limits apply',
  'backup_available': True,
  'backup_note': 'Completed documents are retained by the service.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'ok', 'confidential': 'ok'},
  'audiences': ['team', 'external'],
  'volumes': ['small'],
  'purposes': ['everyday'],
  'pros': ['Approved for all classification levels', 'Easy signing with outside parties'],
  'cons': ['Only for documents that need signatures',
           'Rolling out e-signature workflows needs governance approval'],
  'accent': '#FFC820',
  'pricing': 'quota',
  'eligibility': 'Student employees, faculty, staff, and administrators',
  'how_to': 'Sign in with your university credentials.'},
 {'id': 'cloud_paid',
  'name': 'AWS / Azure Cloud Storage',
  'short_name': 'Cloud Storage',
  'vendor': 'AWS / Azure',
  'category': 'Purchasable cloud storage',
  'tagline': "Pay-as-you-go cloud storage via the university's cloud contracts.",
  'description': "Storage purchased directly through the university's AWS or Microsoft Azure contracts, for "
                 "large-scale or specialized needs that don't fit the standard tiers — e.g. web app "
                 'backends, elastic scaling, or specialized services.',
  'cost': 'Paid, pay-as-you-go',
  'capacity_label': 'Elastic — scales to any size',
  'backup_available': True,
  'backup_note': 'Depends entirely on how you configure it — backup is your responsibility.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'review', 'confidential': 'review'},
  'audiences': ['individual', 'team', 'external'],
  'volumes': ['small', 'medium', 'large', 'xlarge'],
  'purposes': ['everyday', 'hpc', 'archive'],
  'pros': ['Extremely flexible and scalable', 'Good for specialized or elastic workloads'],
  'cons': ['Requires review/approval for sensitive or confidential data',
           'You configure and pay for everything, including backup',
           'Approval rules were written for AWS; confirm Azure terms with IT'],
  'accent': '#232F3E',
  'pricing': 'paid',
  'how_to': "Request a consultation with research computing support to buy through the university's cloud "
            'contracts.',
  'eligibility': "Groups that can pay through the university's contracts"},
 {'id': 'local_drive',
  'name': 'Local Computer Hard Drive',
  'short_name': 'Local Drive',
  'vendor': '—',
  'category': 'Not recommended for permanent storage',
  'tagline': 'The disk inside your own PC or laptop.',
  'description': 'Storage local to a single PC, laptop, or server. Convenient for temporary files, but there '
                 'is no institutional backup or recovery if the device is lost, stolen, or fails.',
  'cost': 'None',
  'capacity_label': 'Whatever your device has free',
  'backup_available': False,
  'backup_note': 'No backup — you are entirely on your own if the device fails.',
  'classification_status': {'unrestricted': 'ok', 'sensitive': 'no', 'confidential': 'no'},
  'audiences': ['individual'],
  'volumes': ['small', 'medium'],
  'purposes': ['everyday'],
  'pros': ['Always available, no setup'],
  'cons': ['No backup or recovery',
           'Never use for sensitive or confidential data',
           'Not meant for permanent storage'],
  'accent': '#8A8A8A',
  'pricing': 'quota'}]


# Every system on the university data classification page ("What data can I keep where?").
# kind "network" rows carry text instead of yes/review/no.
CLASSIFICATION_MATRIX = [
    {"name": "Audio & video conferencing", "unrestricted": "ok", "sensitive": "ok", "confidential": "no"},
    {"name": "AWS infrastructure", "unrestricted": "ok", "sensitive": "review", "confidential": "review"},
    {"name": "Banner", "unrestricted": "ok", "sensitive": "ok", "confidential": "ok"},
    {"name": "Box", "unrestricted": "ok", "sensitive": "ok", "confidential": "review"},
    {"name": "Canvas", "unrestricted": "ok", "sensitive": "ok", "confidential": "no"},
    {"name": "Core", "unrestricted": "ok", "sensitive": "ok", "confidential": "no"},
    {"name": "Data warehouse", "unrestricted": "ok", "sensitive": "ok", "confidential": "ok"},
    {"name": "DocuSign", "unrestricted": "ok", "sensitive": "ok", "confidential": "ok"},
    {"name": "Drupal", "unrestricted": "ok", "sensitive": "no", "confidential": "no"},
    {"name": "Email", "unrestricted": "ok", "sensitive": "no", "confidential": "no"},
    {"name": "Exchange", "unrestricted": "ok", "sensitive": "ok", "confidential": "no"},
    {"name": "Google Drive / Docs", "unrestricted": "ok", "sensitive": "ok", "confidential": "no"},
    {"name": "Microsoft 365 (OneDrive, SharePoint)", "unrestricted": "ok", "sensitive": "ok", "confidential": "ok"},
    {"name": "OnBase", "unrestricted": "ok", "sensitive": "ok", "confidential": "review"},
    {"name": "Network shares (shared drives)", "unrestricted": "ok", "sensitive": "ok", "confidential": "review",
     "note": "Confidential: check with your IT support."},
    {"name": "Qualtrics", "unrestricted": "ok", "sensitive": "ok", "confidential": "review"},
    {"name": "Slack", "unrestricted": "ok", "sensitive": "no", "confidential": "no"},
    {"name": "WordPress", "unrestricted": "ok", "sensitive": "no", "confidential": "no"},
    {"name": "VPN", "unrestricted": "text:Not required", "sensitive": "text:Recommended", "confidential": "text:Required"},
]
